AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Magnolia V2 - Lambda with Dependencies Layer

Parameters:
  DatabaseUrl:
    Type: String
    Description: PostgreSQL connection string
    NoEcho: true
    Default: ''

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        NODE_ENV: production

Resources:
  # Layer for heavy dependencies
  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: magnolia-dependencies
      Description: Heavy dependencies for Magnolia
      ContentUri: ./layer-deps/
      CompatibleRuntimes:
        - nodejs18.x
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: nodejs18.x

  # API Lambda Function (with minimal dependencies)
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: magnolia-v2-api
      CodeUri: ./dist
      Handler: lambda/api-handler.handler
      Layers:
        - !Ref DependenciesLayer
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          ALLOWED_ORIGINS: "http://localhost:5173,http://localhost:3000,http://localhost:3001"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        HealthCheck:
          Type: Api
          Properties:
            Path: /health
            Method: GET

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'