AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Magnolia V2 - Test Lambda

Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: magnolia-test
      Runtime: nodejs18.x
      Handler: index.handler
      InlineCode: |
        exports.handler = async (event) => {
          console.log('Event:', JSON.stringify(event, null, 2));
          
          const path = event.path || '/';
          const method = event.httpMethod || 'GET';
          
          let body = {
            message: 'Magnolia V2 API Test',
            path: path,
            method: method,
            timestamp: new Date().toISOString()
          };
          
          if (path === '/health') {
            body.status = 'healthy';
          }
          
          return {
            statusCode: 200,
            headers: {
              'Content-Type': 'application/json',
              'Access-Control-Allow-Origin': '*'
            },
            body: JSON.stringify(body)
          };
        };
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        RootEvent:
          Type: Api
          Properties:
            Path: /
            Method: GET
        HealthEvent:
          Type: Api
          Properties:
            Path: /health
            Method: GET

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'